"""Seed the AIShopzone database.

Creates all tables (from the SQLAlchemy models) and populates the product
catalog with 50 realistic products across several categories.

Run with:

    python seed_data.py            # add products only if the table is empty
    python seed_data.py --reset    # drop & recreate all tables, then seed

Every product is given its own unique image at
static/images/products/<category-slug>/<n>.svg (generated by
generate_product_images.py). The image fallback chain (product image ->
category image -> placeholder.jpg) is preserved for any product whose image
is somehow missing.
"""
import os
import sys

from app import app
from extensions import db
from models import Product
from utils import category_slug


# (name, category, price, rating, stock, description)
PRODUCTS = [
    # ---------------- Electronics ----------------
    ("Wireless Noise-Cancelling Headphones", "Electronics", 129.99, 4.6, 45,
     "Over-ear Bluetooth headphones with active noise cancellation and 30-hour battery life."),
    ("4K Ultra HD Smart TV 55\"", "Electronics", 499.00, 4.5, 20,
     "55-inch 4K HDR smart TV with built-in streaming apps and voice remote."),
    ("Smartphone Pro 128GB", "Electronics", 799.00, 4.7, 30,
     "Flagship smartphone with triple camera, OLED display, and all-day battery."),
    ("Portable Bluetooth Speaker", "Electronics", 39.99, 4.4, 80,
     "Compact waterproof speaker with rich bass and 12-hour playtime."),
    ("Wireless Charging Pad", "Electronics", 24.99, 4.2, 120,
     "Fast 15W Qi wireless charger compatible with all modern smartphones."),
    ("Mechanical Gaming Keyboard", "Electronics", 89.99, 4.8, 40,
     "RGB backlit mechanical keyboard with hot-swappable switches."),
    ("Smartwatch Fitness Tracker", "Electronics", 149.99, 4.5, 55,
     "Water-resistant smartwatch with heart-rate monitor, GPS, and sleep tracking."),

    # ---------------- Fashion ----------------
    ("Men's Classic Denim Jacket", "Fashion", 59.99, 4.4, 70,
     "Timeless slim-fit denim jacket made from durable cotton blend."),
    ("Women's Running Sneakers", "Fashion", 74.99, 4.6, 65,
     "Lightweight breathable running shoes with cushioned soles."),
    ("Leather Crossbody Bag", "Fashion", 89.00, 4.7, 35,
     "Genuine leather crossbody bag with adjustable strap and multiple compartments."),
    ("Unisex Aviator Sunglasses", "Fashion", 29.99, 4.3, 100,
     "UV400 polarized aviator sunglasses with a lightweight metal frame."),
    ("Cotton Crew-Neck T-Shirt", "Fashion", 19.99, 4.2, 200,
     "Soft breathable 100% cotton t-shirt available in everyday colors."),
    ("Wool Blend Winter Scarf", "Fashion", 24.99, 4.5, 90,
     "Cozy wool-blend scarf that keeps you warm through the cold season."),
    ("Analog Wrist Watch", "Fashion", 119.00, 4.6, 25,
     "Minimalist analog watch with stainless steel case and leather strap."),

    # ---------------- Home & Kitchen ----------------
    ("Stainless Steel Cookware Set", "Home & Kitchen", 159.99, 4.7, 18,
     "10-piece stainless steel cookware set with tempered glass lids."),
    ("Programmable Coffee Maker", "Home & Kitchen", 69.99, 4.4, 40,
     "12-cup programmable drip coffee maker with reusable filter."),
    ("Air Fryer 5L", "Home & Kitchen", 99.99, 4.6, 33,
     "Digital 5-liter air fryer for oil-free frying, baking, and roasting."),
    ("Memory Foam Pillow", "Home & Kitchen", 34.99, 4.5, 110,
     "Ergonomic memory foam pillow with cooling gel cover for better sleep."),
    ("LED Desk Lamp", "Home & Kitchen", 27.99, 4.3, 85,
     "Adjustable LED desk lamp with touch dimming and USB charging port."),
    ("Ceramic Dinnerware Set", "Home & Kitchen", 79.99, 4.4, 28,
     "16-piece ceramic dinnerware set, dishwasher and microwave safe."),
    ("Robot Vacuum Cleaner", "Home & Kitchen", 229.00, 4.5, 15,
     "Smart robot vacuum with app control, mapping, and auto-charging."),
    ("Glass Food Storage Containers", "Home & Kitchen", 32.99, 4.6, 95,
     "Set of 10 airtight glass containers with leak-proof snap lids."),

    # ---------------- Books ----------------
    ("The Art of Clean Code", "Books", 34.99, 4.8, 50,
     "A practical guide to writing readable, maintainable software."),
    ("Mystery of the Silent Lake", "Books", 14.99, 4.5, 75,
     "A gripping thriller novel full of twists and unexpected turns."),
    ("Cooking for Beginners", "Books", 22.50, 4.4, 60,
     "Step-by-step recipes and techniques for the home cook."),
    ("World History Illustrated", "Books", 45.00, 4.6, 30,
     "A richly illustrated journey through major events in world history."),
    ("Mindful Living Journal", "Books", 12.99, 4.3, 120,
     "A guided journal to help you build daily mindfulness habits."),
    ("Space Explorers (Kids)", "Books", 18.99, 4.7, 80,
     "An illustrated children's book about planets, stars, and galaxies."),

    # ---------------- Toys & Games ----------------
    ("Building Blocks Set 500pc", "Toys & Games", 39.99, 4.7, 65,
     "Creative 500-piece building block set compatible with major brands."),
    ("Remote Control Race Car", "Toys & Games", 44.99, 4.4, 40,
     "High-speed RC car with rechargeable battery and 2.4GHz control."),
    ("Family Board Game", "Toys & Games", 29.99, 4.6, 55,
     "A fun strategy board game for 2-6 players, ages 8 and up."),
    ("Plush Teddy Bear", "Toys & Games", 19.99, 4.8, 100,
     "Super-soft cuddly teddy bear, perfect gift for all ages."),
    ("1000-Piece Jigsaw Puzzle", "Toys & Games", 16.99, 4.5, 70,
     "Challenging 1000-piece landscape jigsaw puzzle for the whole family."),
    ("Wooden Chess Set", "Toys & Games", 49.99, 4.7, 25,
     "Handcrafted wooden chess set with a folding storage board."),

    # ---------------- Beauty ----------------
    ("Vitamin C Face Serum", "Beauty", 24.99, 4.6, 90,
     "Brightening vitamin C serum with hyaluronic acid for glowing skin."),
    ("Matte Lipstick Set", "Beauty", 29.99, 4.4, 75,
     "Set of 6 long-lasting matte lipsticks in versatile shades."),
    ("Natural Shampoo & Conditioner", "Beauty", 21.99, 4.5, 110,
     "Sulfate-free shampoo and conditioner duo with argan oil."),
    ("Electric Facial Cleansing Brush", "Beauty", 39.99, 4.3, 45,
     "Rechargeable silicone facial brush for deep pore cleansing."),
    ("Aromatherapy Essential Oil Set", "Beauty", 27.99, 4.6, 60,
     "Set of 6 pure essential oils for diffusers and relaxation."),
    ("Makeup Brush Kit", "Beauty", 34.99, 4.5, 50,
     "Professional 12-piece makeup brush kit with a travel case."),

    # ---------------- Sports & Outdoors ----------------
    ("Yoga Mat with Strap", "Sports & Outdoors", 25.99, 4.6, 85,
     "Non-slip 6mm yoga mat with carrying strap, ideal for all workouts."),
    ("Adjustable Dumbbell Set", "Sports & Outdoors", 149.99, 4.7, 20,
     "Space-saving adjustable dumbbells, 5-52.5 lbs per handle."),
    ("Insulated Water Bottle 1L", "Sports & Outdoors", 22.99, 4.5, 130,
     "Vacuum-insulated stainless steel bottle keeps drinks cold 24 hours."),
    ("2-Person Camping Tent", "Sports & Outdoors", 89.99, 4.4, 30,
     "Lightweight waterproof tent that sets up in minutes."),
    ("Foam Roller", "Sports & Outdoors", 19.99, 4.5, 95,
     "High-density foam roller for muscle recovery and deep tissue massage."),
    ("Cycling Helmet", "Sports & Outdoors", 44.99, 4.6, 40,
     "Lightweight ventilated helmet with adjustable fit dial."),

    # ---------------- Grocery ----------------
    ("Organic Green Tea (100 bags)", "Grocery", 14.99, 4.6, 150,
     "Premium organic green tea, individually wrapped for freshness."),
    ("Extra Virgin Olive Oil 1L", "Grocery", 18.99, 4.7, 100,
     "Cold-pressed extra virgin olive oil from Mediterranean groves."),
    ("Dark Chocolate Assortment", "Grocery", 21.99, 4.8, 80,
     "Luxury assorted dark chocolate box, 70% cocoa, gift-ready."),
    ("Mixed Nuts 1kg", "Grocery", 24.99, 4.5, 90,
     "Roasted unsalted mixed nuts, a healthy protein-rich snack."),
]


def seed(reset=False):
    with app.app_context():
        if reset:
            print("Dropping all tables...")
            db.drop_all()

        print("Creating all tables...")
        db.create_all()

        existing = Product.query.count()
        if existing and not reset:
            print(f"Products table already has {existing} rows; skipping seed. "
                  "Use --reset to reseed.")
            return

        print(f"Seeding {len(PRODUCTS)} products...")
        for idx, (name, category, price, rating, stock, description) in enumerate(PRODUCTS, start=1):
            # Each product gets its own unique, pre-generated image. We verify
            # the file actually exists before referencing it so the catalog
            # never points at a missing image.
            image_url = f"images/products/{category_slug(category)}/{idx}.svg"
            rel = os.path.join(app.static_folder, image_url)
            assert os.path.isfile(rel), f"Missing product image for #{idx} {name}: {rel}"

            db.session.add(Product(
                name=name,
                category=category,
                price=price,
                image_url=image_url,
                rating=rating,
                stock=stock,
                description=description,
            ))
        db.session.commit()

        total = Product.query.count()
        categories = sorted({p.category for p in Product.query.all()})
        print(f"Done. {total} products across {len(categories)} categories:")
        for c in categories:
            n = Product.query.filter_by(category=c).count()
            print(f"  - {c}: {n}")


if __name__ == "__main__":
    seed(reset="--reset" in sys.argv)
